- id: doi:10.1116/6.0004029
  image: /images/papers/FilteringTheBeamFromAnIonicLiquidIonSource2024.webp
 
- id: doi:10.1016/j.ultramic.2024.114024
  image: /images/papers/Ultramicroscopy2024.webp
  
- id: doi:10.1088/1361-648X/ac03d3
  image: /images/papers/ControllingAdhesionUsingACFieldsAcrossFluidFilms2021.webp

- id: doi:10.1021/acs.jpclett.0c03718
  image: /images/papers/WaterInSaltElectrolytes2021.jpeg
  
- id: doi:10.1021/acs.langmuir.9b01415
  image: /images/papers/Langmuir2019.png
  
- id: doi:10.1039/c9sm00487d
  image: /images/papers/SoftMatterCholesteric.png

- id: doi:10.1039/c9sm00143c
  image: /images/papers/SoftMatterEfield2019.png 
  
- id: doi:10.1103/PhysRevLett.119.026002
  image: /images/papers/PRL2017.png
  
- id: doi:10.1039/c6fd00250a

- id: doi:10.1063/1.4927481
  image: /images/papers/IonFieldEvaporationFromIonicLiquidsInfusingCarbonXerogelMicrotips.webp

- id: doi:10.1016/j.mee.2014.02.032

- id: doi:10.1016/j.mee.2010.12.037

- id: doi:10.1016/j.mee.2010.11.042

- id: doi:10.1116/1.4745187
  image: images/papers/JSVTB2012.png

- id: doi:10.1116/1.3432125
  image: /images/papers/DevelopmentOfIonSourcesFromIonicLiquidsForMicrofabrication2010.webp

